### ISSUE TITLE
Error caused by getting empty hgvs df

### ISSUE THREAD

**Issue by RyogaLi** [RyogaLi/tileseq_mutcount#14]
Traceback (most recent call last):
  File "/home/rothlab2/rli/.conda/envs/py37/bin/tileseq_mut", line 41, in <module>
    main(args)
  File "/home/rothlab2/rli/.conda/envs/py37/lib/python3.7/site-packages/TileSeqMut/main.py", line 502, in main
    mc._main()
  File "/home/rothlab2/rli/.conda/envs/py37/lib/python3.7/site-packages/TileSeqMut/main.py", line 340, in _main
    self._mut_count()
  File "/home/rothlab2/rli/.conda/envs/py37/lib/python3.7/site-packages/TileSeqMut/main.py", line 252, in _mut_count
    mut_counts.multi_core()
  File "/home/rothlab2/rli/.conda/envs/py37/lib/python3.7/site-packages/TileSeqMut/count_mut.py", line 460, in multi_core
    hgvs_df.columns = ["HGVS", "count"]
  File "/home/rothlab2/rli/.conda/envs/py37/lib/python3.7/site-packages/pandas/core/generic.py", line 5152, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 66, in pandas._libs.properties.AxisProperty.__set__
  File "/home/rothlab2/rli/.conda/envs/py37/lib/python3.7/site-packages/pandas/core/generic.py", line 564, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/rothlab2/rli/.conda/envs/py37/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 227, in set_axis
    f"Length mismatch: Expected axis has {old_len} elements, new "
ValueError: Length mismatch: Expected axis has 1 elements, new values have 2 elements

**Comment by RyogaLi** [comment]
ryogali@596da26c9036816edf90954565ba1445855e80e3
